name = "workers-tunnel"
main = "build/worker/shim.mjs"
compatibility_date = "2024-09-02"

[build]
command = "cargo install -q worker-build && worker-build --release"

[observability]
enabled = true
head_sampling_rate = 1

[vars]
USER_ID = "b788cfd4-43ff-475e-b36d-b65d18a1d172" # your uuid
PROXY_IP = "proxyip.fxxk.dedyn.io" # proxyip.fxxk.dedyn.io
FALLBACK_SITE = "https://httpbin.org/status/404" # https://httpbin.org/status/404
SHOW_URI = "true" # show vless uri in /UUID path
